"use client"; // Adiciona a diretiva para o Next.js

import React, { useState } from 'react';
import { ShieldCheck, TrendingUp, Cpu, Bell, Database, Zap, Lock, AlertTriangle, Blocks } from 'lucide-react';

// Tipagem para os props do Header
interface HeaderProps {
  setPage: (page: string) => void;
  activePage: string;
}

// Componente: Header (Barra de Navegação)
const Header: React.FC<HeaderProps> = ({ setPage, activePage }) => {
  const navItems = [
    { name: 'Home', page: 'home' },
    { name: 'Analytics', page: 'analytics' },
    { name: 'AI Signals', page: 'signals' },
    { name: 'Security & Risk Detection', page: 'security' }, // Nova página
  ];

  const getLinkClass = (page: string) => {
    return `cursor-pointer rounded-md px-3 py-2 text-sm font-medium transition-colors ${
      activePage === page
        ? 'bg-indigo-700 text-white'
        : 'text-gray-300 hover:bg-gray-700 hover:text-white'
    }`;
  };

  return (
    <nav className="bg-gray-900/80 backdrop-blur-sm shadow-lg sticky top-0 z-50">
      <div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
        <div className="flex h-16 items-center justify-between">
          <div className="flex-shrink-0">
            {/* Logo */}
            <span
              onClick={() => setPage('home')}
              className="flex items-center space-x-2 cursor-pointer"
            >
              <TrendingUp className="h-8 w-8 text-indigo-400" />
              <span className="text-2xl font-bold text-white">ProphetFi</span>
            </span>
          </div>
          <div className="hidden md:block">
            <div className="ml-10 flex items-baseline space-x-4">
              {navItems.map((item) => (
                <a
                  key={item.name}
                  onClick={() => setPage(item.page)}
                  className={getLinkClass(item.page)}
                >
                  {item.name}
                </a>
              ))}
            </div>
          </div>
          <div className="hidden md:block">
            <button className="rounded-md bg-indigo-600 px-4 py-2 text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600 transition-all">
              Launch App
            </button>
          </div>
        </div>
      </div>
    </nav>
  );
};

// Componente: Hero Section (Parte da Home Page)
const HeroSection: React.FC = () => (
  <div className="relative isolate overflow-hidden bg-gray-900 pt-16 pb-24 sm:pt-24 sm:pb-32">
    {/* Fundo Gradiente */}
    <div
      aria-hidden="true"
      className="absolute inset-x-0 -top-40 -z-10 transform-gpu overflow-hidden blur-3xl sm:-top-80"
    >
      <div
        style={{
          clipPath:
            'polygon(74.1% 44.1%, 100% 61.6%, 97.5% 26.9%, 85.5% 0.1%, 80.7% 2%, 72.5% 32.5%, 60.2% 62.4%, 52.4% 68.1%, 47.5% 58.3%, 45.2% 34.5%, 27.5% 76.7%, 0.1% 64.9%, 17.9% 100%, 27.6% 76.8%, 76.1% 97.7%, 74.1% 44.1%)',
        }}
        className="relative left-[calc(50%-11rem)] aspect-[1155/678] w-[36.125rem] -translate-x-1/2 rotate-[30deg] bg-gradient-to-tr from-[#8085ff] to-[#3B0764] opacity-30 sm:left-[calc(50%-30rem)] sm:w-[72.1875rem]"
      />
    </div>
    <div className="mx-auto max-w-7xl px-6 lg:px-8">
      <div className="mx-auto max-w-3xl text-center">
        <h1 className="text-4xl font-bold tracking-tight text-white sm:text-6xl">
          The Future of DeFi Intelligence
        </h1>
        <p className="mt-6 text-lg leading-8 text-gray-300">
          ProphetFi leverages next-generation AI to provide predictive market insights, real-time risk assessment, and institutional-grade security for users and protocols.
        </p>
        <div className="mt-10 flex items-center justify-center gap-x-6">
          <button className="rounded-md bg-indigo-600 px-5 py-3 text-base font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600 transition-all">
            Get Started
          </button>
          <a href="#features" className="text-base font-semibold leading-6 text-white hover:text-gray-200">
            Learn More <span aria-hidden="true">→</span>
          </a>
        </div>
      </div>
    </div>
  </div>
);

// Componente: Features (Parte da Home Page)
const FeaturesSection: React.FC = () => {
  const features = [
    {
      name: 'Predictive Analytics',
      description: 'Our AI models analyze terabytes of on-chain and off-chain data to forecast market trends before they happen.',
      icon: TrendingUp,
    },
    {
      name: 'Real-Time AI Signals',
      description: 'Receive actionable buy/sell/hold signals generated by our proprietary AI, tailored to your risk profile.',
      icon: Bell,
    },
    {
      name: 'Total Protocol Security',
      description: 'Protect your users and your treasury with our real-time threat detection and automated security responses.',
      icon: ShieldCheck,
    },
    {
      name: 'Deep On-Chain Data',
      description: 'Go beyond the surface. Access deep wallet tracking, liquidity flow analysis, and smart contract auditing.',
      icon: Database,
    },
    {
      name: 'AI-Powered Smart Contracts',
      description: 'Develop and deploy adaptive smart contracts that react to market conditions and security threats automatically.',
      icon: Cpu,
    },
    {
      name: 'Instant Risk Detection',
      description: 'Instantly score any token or protocol for rug pull, exploit, or governance risks. (B2B & B2C)',
      icon: Zap,
    },
  ];

  return (
    <div id="features" className="bg-gray-900 py-24 sm:py-32">
      <div className="mx-auto max-w-7xl px-6 lg:px-8">
        <div className="mx-auto max-w-2xl lg:text-center">
          <p className="text-base font-semibold leading-7 text-indigo-400">Why ProphetFi?</p>
          <h2 className="mt-2 text-3xl font-bold tracking-tight text-white sm:text-4xl">
            An Unfair Advantage in DeFi
          </h2>
          <p className="mt-6 text-lg leading-8 text-gray-300">
            Stop guessing. Start predicting. Our platform provides the critical intelligence you need to navigate the complexities of decentralized finance with confidence.
          </p>
        </div>
        <div className="mx-auto mt-16 max-w-2xl sm:mt-20 lg:mt-24 lg:max-w-none">
          <dl className="grid max-w-xl grid-cols-1 gap-x-8 gap-y-16 lg:max-w-none lg:grid-cols-3">
            {features.map((feature) => (
              <div key={feature.name} className="flex flex-col p-6 rounded-lg bg-gray-800/50 shadow-lg transition-all hover:scale-105 hover:bg-gray-800">
                <dt className="flex items-center gap-x-3 text-lg font-semibold leading-7 text-white">
                  <feature.icon className="h-6 w-6 flex-none text-indigo-400" aria-hidden="true" />
                  {feature.name}
                </dt>
                <dd className="mt-4 flex flex-auto flex-col text-base leading-7 text-gray-300">
                  <p className="flex-auto">{feature.description}</p>
                </dd>
              </div>
            ))}
          </dl>
        </div>
      </div>
    </div>
  );
};

// Componente: Home Page (Combina Hero e Features)
const HomePage: React.FC = () => (
  <>
    <HeroSection />
    <FeaturesSection />
  </>
);

// Componente: Security & Risk Detection Page
const SecurityPage: React.FC = () => {
  const signals = [
    {
      name: 'Liquidity Unlocking',
      description: 'The AI flags when a developer or whale unlocks a large, critical portion of a token\'s liquidity pool.',
      icon: Lock,
    },
    {
      name: 'Panic-Inducing Sales',
      description: 'Detection of strategic small sales designed to create market panic and drive the price down.',
      icon: AlertTriangle,
    },
    {
      name: 'Sudden Liquidity Removal',
      description: 'The primary alert. The AI detects the moment the main liquidity is suddenly drained from the pool.',
      icon: Zap,
    },
    {
      name: 'Token Holder Concentration',
      description: 'Monitors if a small number of wallets hold a dangerous percentage of the token supply.',
      icon: Blocks,
    },
  ];

  return (
    <div className="bg-gray-900 py-24 sm:py-32">
      <div className="mx-auto max-w-7xl px-6 lg:px-8">
        {/* Cabeçalho da Página */}
        <div className="mx-auto max-w-3xl lg:text-center">
          <p className="text-base font-semibold leading-7 text-indigo-400">B2B & B2C SaaS Security</p>
          <h1 className="mt-2 text-3xl font-bold tracking-tight text-white sm:text-4xl">
            Security & Real-Time Risk Detection
          </h1>
          <p className="mt-6 text-lg leading-8 text-gray-300">
            Our AI acts as a real-time security system for the entire DeFi ecosystem. We protect users from threats and provide protocols with the tools to safeguard their communities.
          </p>
        </div>

        {/* Seção Principal */}
        <div className="mt-16 sm:mt-24">
          <div className="grid grid-cols-1 gap-16 lg:grid-cols-2 lg:gap-x-12">
            
            {/* Coluna Esquerda: Descrição */}
            <div className="flex flex-col justify-center">
              <h2 className="text-2xl font-bold tracking-tight text-white sm:text-3xl">
                Real-Time "Rug Pull" Detection
              </h2>
              <p className="mt-6 text-lg leading-8 text-gray-300">
                Our AI is trained to recognize the patterns of a "rug pull" *before* it's completed, giving you time to act.
              </p>
              <p className="mt-4 text-lg leading-8 text-gray-300">
                This crucial (B2B & B2C) SaaS feature provides a real-time risk score for any token. When a high-risk pattern is detected, our platform automatically sends an alert to all users holding that token, and to the protocol's team.
              </p>
            </div>

            {/* Coluna Direita: Sinais da IA */}
            <div className="flex flex-col gap-y-8">
              <h3 className="text-xl font-semibold text-white">Signals Our AI Detects:</h3>
              {signals.map((signal) => (
                <div key={signal.name} className="relative flex items-start p-4 rounded-lg bg-gray-800/60 shadow-md">
                  <div className="flex-shrink-0">
                    <signal.icon className="h-8 w-8 text-indigo-400" aria-hidden="true" />
                  </div>
                  <div className="ml-4">
                    <h4 className="text-lg font-semibold leading-7 text-white">{signal.name}</h4>
                    <p className="mt-1 text-base leading-7 text-gray-300">{signal.description}</p>
                  </div>
                </div>
              ))}
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};


// Componente: Footer
const Footer: React.FC = () => (
  <footer className="bg-gray-900 border-t border-gray-700/50 mt-32">
    <div className="mx-auto max-w-7xl overflow-hidden px-6 py-12 lg:px-8">
      <nav className="-mb-6 columns-2 sm:flex sm:justify-center sm:space-x-12" aria-label="Footer">
        {['About', 'Blog', 'Jobs', 'Partners', 'Press'].map((item) => (
          <div key={item} className="pb-6">
            <a href="#" className="text-sm leading-6 text-gray-400 hover:text-white">
              {item}
            </a>
          </div>
        ))}
      </nav>
      <p className="mt-10 text-center text-xs leading-5 text-gray-500">
        &copy; {new Date().getFullYear()} ProphetFi, Inc. All rights reserved.
      </p>
    </div>
  </footer>
);

// Componente Principal: App (Controla a navegação)
export default function App() {
  const [page, setPage] = useState<string>('home'); // 'home' ou 'security'

  return (
    <div className="min-h-screen bg-gray-900 text-white font-sans antialiased">
      {/* Passa o estado da página e o setter para o Header */}
      <Header setPage={setPage} activePage={page} />
      
      <main>
        {/* Renderização Condicional da Página */}
        {page === 'home' && <HomePage />}
        {page === 'security' && <SecurityPage />}
        {/* Adicione outras páginas aqui com 'else if' */}
        {/* {page === 'analytics' && <AnalyticsPage />} */}
        {/* {page === 'signals' && <SignalsPage />} */}
      </main>

      <Footer />
    </div>
  );
}

